### ISSUE TITLE
Create first version of debarcoding operator

### ISSUE THREAD

**Issue by agouy** [tercen/debarcoding_cytof_operator#1]

**Comment by tsmonteiro** [comment]
First working version is now available as 0.0.1. Below are the workflow view, input projection and example output projection, all of which might still change based on validation.

![image](https://user-images.githubusercontent.com/10157888/196752672-e3042ad9-4117-47fc-a133-aa393f41e338.png)

![image](https://user-images.githubusercontent.com/10157888/196753017-6b6a32cf-4af1-4691-989e-2757a229f9a2.png)

![image](https://user-images.githubusercontent.com/10157888/196753130-78224903-1048-4837-ba9a-1d56719a6489.png)

In this last image, the assignment filter is not necessary.

**Comment by tsmonteiro** [comment]
Multiple files are supported (I have concatenated the same input file twice and changed filename to run this test)
