### ISSUE TITLE
Debarcoding multi-step - refactor to work with actual data from the debarcoding scheme file, not the documentId

### ISSUE THREAD

**Issue by makostadima** [tercen/debarcoding_cytof_operator#7]
At the moment the debarcoding scheme file needs to be uploaded onto Tercen as a file to work with the debarcoding operator, not read in as a data set.

It'd be ideal to have it read in as a normal dataset using the delimiter text operator, Gather the data and diaply it on the crosstab view in the debarcoding multi-data step.

**Comment by tsmonteiro** [comment]
Hi Myrto,

Would the projection in the picture below work for working with the sample key file projection? I am not sure this example dataset covers all use cases, file structure and types, though.

![image](https://github.com/tercen/debarcoding_cytof_operator/assets/10157888/8552b6bb-c238-43e9-af4b-44c063f03078)


![image](https://github.com/tercen/debarcoding_cytof_operator/assets/10157888/e7ab4930-2c0f-4d10-853a-22e200f7688d)

**Comment by agouy** [comment]
@tsmonteiro That's what we had in mind, you can go ahead with this input projection. Unrelated question: are we expecting missing data in the sample key here?

**Comment by tsmonteiro** [comment]
At least in this projection, there is no missing data. I am not sure why there are empty cells in the crosstab, but the table correctly display all 120 values.

**Comment by tsmonteiro** [comment]
Issue solved in version 0.3.0

Now you can either have a projection like in the previous comment or a csv object as it was before. For the latter, a documentId column is required and automatically detected.
